Practice/Controllers/AcademyEventsController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PersonManagement.Domain.POCO;
using PersonManagement.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace PersonManagement.MVC.Controllers
{
    public class AcademyEventsController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var url = Constants.ApiUrl + "academyEvent";
            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var academyEvents = JsonConvert
                .DeserializeObject<List<AcademyEvent>>(json)
                .Where(x => x.IsApproved)
                .Select(a => a.Adapt<AcademyEventViewModel>());

            return View(academyEvents); //success
        }

        public async Task<ActionResult> My()
        {
            var url = Constants.ApiUrl + "users/" + GetUserLogin() + "/academyEvents";
            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var academyEvents = JsonConvert
                .DeserializeObject<List<AcademyEvent>>(json)
                .Where(x => x.IsApproved)
                .Select(a => a.Adapt<AcademyEventViewModel>());

            return View(academyEvents);
        }

        public async Task<ActionResult> Details(int id)
        {
            var url = Constants.ApiUrl + "academyEvent/" + id;

            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var academyEvent = JsonConvert
                .DeserializeObject<AcademyEvent>(json)
                .Adapt<AcademyEventViewModel>();

            return View(academyEvent);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(AcademyEventViewModel viewModel)
        {
            var academyEvent = viewModel.Adapt<AcademyEvent>();
            academyEvent.AuthorUsername = GetUserLogin();
            academyEvent.CreatedAt = DateTime.Now;
            var url = Constants.ApiUrl + "academyEvent";
            var json = JsonConvert.SerializeObject(academyEvent);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await PostResponse(url, data);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return RedirectToAction("Index"); //success
        }

        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Update(AcademyEventViewModel viewModel)
        {
            var academyEvent = viewModel.Adapt<AcademyEvent>();
            
            var url = Constants.ApiUrl + "academyEvent";
            var json = JsonConvert.SerializeObject(academyEvent);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await PutResponse(url, data);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return View(); //success
        }

        private async Task<HttpResponseMessage> PostResponse(string url, HttpContent data)
        {
            using var client = new HttpClient();
            var response = await client.PostAsync(url, data);

            return response;
        }

        private async Task<HttpResponseMessage> PutResponse(string url, HttpContent data)
        {
            using var client = new HttpClient();
            var response = await client.PutAsync(url, data);

            return response;
        }

        private async Task<HttpResponseMessage> GetResponse(string url)
        {
            using var client = new HttpClient();
            var response = await client.GetAsync(url);

            return response;
        }

        private string GetUserLogin()
        {
            return Token.GetLoginFromToken(Request.Cookies.FirstOrDefault(x => x.Key == Constants.Token).Value);
        }
    }
}

Practice/Controllers/AdminController.cs
using Mapster;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PersonManagement.Api.Models;
using PersonManagement.Domain.POCO;
using PersonManagement.MVC.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace PersonManagement.MVC.Controllers
{
    [Route("[controller]")]
    public class AdminController : Controller
    {
        [HttpGet]
        [Route("academyEvents")]
        public async Task<ActionResult> Index()
        {
            var url = Constants.ApiUrl + "academyEvent";
            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var academyEvents = JsonConvert
                .DeserializeObject<List<AcademyEvent>>(json)
                .Where(x => x.IsApproved)
                .Select(a => a.Adapt<AcademyEventViewModel>());

            return View(academyEvents); //success
        }

        [HttpGet]
        [Route("academyevents/update/{id}")]
        public async Task<ActionResult> Update(int id)
        {
            var url = Constants.ApiUrl + "academyEvent/" + id;

            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var academyEvent = JsonConvert
                .DeserializeObject<AcademyEvent>(json)
                .Adapt<AcademyEventViewModel>();

            return View(academyEvent);
        }

        [HttpPost]
        [Route("academyevents/update/{id}")]
        public async Task<ActionResult> Update(int id, AcademyEventViewModel viewModel)
        {
            var academyEvent = viewModel.Adapt<AcademyEvent>();
            academyEvent.Id = id;
            academyEvent.IsApproved = true;
            var url = Constants.ApiUrl + "academyEvent/" + id;
            var json = JsonConvert.SerializeObject(academyEvent);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await PutRequest(url, data);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return RedirectToAction("Index"); //success
        }

        [HttpGet]
        [Route("academyevents/delete/{id}")]
        public async Task<ActionResult> Delete(int id)
        {
            var url = Constants.ApiUrl + "academyEvent/" + id;
            var response = await DeleteResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("academyevents/pending")]
        public async Task<ActionResult> Pending()
        {
            var url = Constants.ApiUrl + "academyEvent/pending";
            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var pendingAcademyEvents = JsonConvert
                .DeserializeObject<List<AcademyEvent>>(json)
                .Select(a => a.Adapt<AcademyEventViewModel>());

            return View(pendingAcademyEvents); //success
        }

        [HttpGet]
        [Route("academyevents/approve/{id}")]
        public async Task<ActionResult> Approve(int id, AcademyEventViewModel viewModel)
        {
            var url = Constants.ApiUrl + "academyEvent/" + id;

            var response = await GetResponse(url);

            var json = await response.Content.ReadAsStringAsync();
            var academyEvent = JsonConvert
                .DeserializeObject<AcademyEvent>(json);

            academyEvent.Id = id;
            academyEvent.IsApproved = true;
            url = Constants.ApiUrl + "academyEvent/" + id;
            json = JsonConvert.SerializeObject(academyEvent);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            response = await PutRequest(url, data);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return RedirectToAction("Index"); //success
        }

        [HttpGet]
        [Route("users")]
        public async Task<ActionResult> GetUsers()
        {
            var url = Constants.ApiUrl + "users";
            var response = await GetResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            var json = await response.Content.ReadAsStringAsync();
            var users = JsonConvert
                .DeserializeObject<List<IdentityUser>>(json);

            var variable = users.Adapt<List<UserViewModel>>();

                //.Select(a => a.Adapt<UserViewModel>());

            return View(variable); //success
        }

        [HttpGet]
        [Route("users/create")]
        public ActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        [Route("users/create")]
        public async Task<ActionResult> CreateUser(string username, string email, string password)
        {
            var url = Constants.ApiUrl + "auth/" + "register";
            var json = JsonConvert.SerializeObject(new RegisterModel(username, email, password));
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await PostResponse(url, data);

            if (!response.IsSuccessStatusCode)
            {
                var responseJson = await response.Content.ReadAsStringAsync();
                JObject obj = JObject.Parse(responseJson);
                var errors = obj["errors"].ToList();

                return View(errors); //errors view
            }

            return View();
        }

        [HttpGet]
        [Route("users/delete/{username}")]
        public async Task<ActionResult> DeleteUser(string username)
        {
            var url = Constants.ApiUrl + "users/" + username;
            var response = await DeleteResponse(url);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //not found
            }

            return RedirectToAction("GetUsers"); //success
        }

        private async Task<HttpResponseMessage> PutRequest(string url, HttpContent data)
        {
            using var client = new HttpClient();
            var response = await client.PutAsync(url, data);

            return response;
        }

        private async Task<HttpResponseMessage> PostResponse(string url, HttpContent data)
        {
            using var client = new HttpClient();
            var response = await client.PostAsync(url, data);

            return response;
        }

        private async Task<HttpResponseMessage> GetResponse(string url)
        {
            using var client = new HttpClient();
            var response = await client.GetAsync(url);

            return response;
        }

        private async Task<HttpResponseMessage> DeleteResponse(string url)
        {
            using var client = new HttpClient();
            var response = await client.DeleteAsync(url);

            return response;
        }

        private string GetUserLogin()
        {
            return Token.GetLoginFromToken(Request.Cookies.FirstOrDefault(x => x.Key == Constants.Token).Value);
        }
    }
}

Practice/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PersonManagement.Api.Models;
using System;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace PersonManagement.MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        private const string ApiEndpoint = "auth/";

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(string username, string email, string password)
        {
            var url = Constants.ApiUrl + ApiEndpoint + "register";
            var json = JsonConvert.SerializeObject(new RegisterModel(username, email, password));
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await GetResponse(url, data);

            if (!response.IsSuccessStatusCode)
			{
                return View(); //error
            }

            return RedirectToAction(nameof(Login));
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string login, string password)
        {
            var url = Constants.ApiUrl + ApiEndpoint + "login";
            var json = JsonConvert.SerializeObject(new LoginModel(login, password));
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await GetResponse(url, data);

            if (!response.IsSuccessStatusCode)
            {
                return View(); //error
            }

            CookieOptions cookieOptions = new CookieOptions
            {
                Expires = DateTime.Now.AddMinutes(Constants.TokenExpirationTimeInMinutes),
                Secure = true
            };
            Response.Cookies.Append(Constants.Token, Token.GenerateToken(login), cookieOptions);

            return RedirectToAction("Index", "AcademyEvents");
        }
        public IActionResult Signout()
        {
            var token = Request.Cookies.FirstOrDefault(x => x.Key == Constants.Token);

            if (token.Key != null)
            {
                Response.Cookies.Delete(Constants.Token);
            }

            return RedirectToAction(nameof(Login));
        }

		private async Task<HttpResponseMessage> GetResponse(string url, StringContent data)
        {
            using var client = new HttpClient();
            var response = await client.PostAsync(url, data);

            return response;
        }
    }
}

Practice/Views/Admin/Create.cshtml
@model PersonManagement.MVC.ViewModels.AcademyEventViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>AcademyEventViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAndTime" class="control-label"></label>
                <input asp-for="DateAndTime" class="form-control" />
                <span asp-validation-for="DateAndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorUsername" class="control-label"></label>
                <input asp-for="AuthorUsername" class="form-control" />
                <span asp-validation-for="AuthorUsername" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<a class="btn btn-danger" asp-controller="AcademyEvents" asp-action="My">See events</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practice/Views/Admin/CreateUser.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h3>
    Create user page
</h3>
<form asp-controller="Admin" asp-action="CreateUser" method="post">
    <label for="email"><b>Email</b></label>
    <input type="text" name="userName" value="" id="email" />

    <label for="psw"><b>Password</b></label>
    <input type="password" name="password" value="" id="psw" />

    <label for="psw"><b>Repeat password</b></label>
    <input type="password" name="password" value="" id="psw-repeat" />

    <button type="submit" class="btn btn-primary registerbtn"> Create user </button>
</form>

<br>
<a class="btn btn-danger" asp-controller="Admin" asp-action="GetUsers">Return back to users</a>

Practice/Views/Admin/DeleteUser.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<h1>User deleted successfully!</h1>
<h2><a asp-controller="Admin" asp-action="DeleteUser">Return back</a></h2>

Practice/Views/Admin/Details.cshtml
@model PersonManagement.MVC.ViewModels.AcademyEventViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AcademyEventViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateAndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateAndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorUsername)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AuthorUsername)
        </dd>
    </dl>
</div>

<a class="btn btn-primary" asp-controller="Authentication" asp-action="Index">Return back</a>

Practice/Views/Admin/GetUsers.cshtml
@model IEnumerable<PersonManagement.MVC.ViewModels.UserViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "GetUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>GetUsers</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteUser", new { username = item.UserName })
            </td>
        </tr>
        }
    </tbody>
</table>

<a class="btn btn-danger" asp-controller="Authentication" asp-action="Signout">Sign out</a>

Practice/Views/Admin/Index.cshtml
@model IEnumerable<PersonManagement.MVC.ViewModels.AcademyEventViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorUsername)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImgUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorUsername)
            </td>
            <td>
                @Html.ActionLink("Update", "Update", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

<a class="btn btn-danger" asp-controller="Authentication" asp-action="Signout">Sign out</a>

Practice/Views/Admin/My.cshtml
@model IEnumerable<PersonManagement.MVC.ViewModels.AcademyEventViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "My";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>My</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorUsername)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImgUrl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorUsername)
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-danger" asp-controller="Authentication" asp-action="Index">Return back</a>

Practice/Views/Admin/Pending.cshtml
@model IEnumerable<PersonManagement.MVC.ViewModels.AcademyEventViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Pending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Pending</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorUsername)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImgUrl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorUsername)
                </td>
                <td>
                    @Html.ActionLink("Approve", "Approve", new { id = item.Id }) |
                    @Html.ActionLink("Reject", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-danger" asp-controller="Admin" asp-action="Index">Return back</a>

Practice/Views/Admin/Update.cshtml
@model PersonManagement.MVC.ViewModels.AcademyEventViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>

<h4>AcademyEventViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAndTime" class="control-label"></label>
                <input asp-for="DateAndTime" class="form-control" />
                <span asp-validation-for="DateAndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorUsername" class="control-label"></label>
                <input asp-for="AuthorUsername" class="form-control" />
                <span asp-validation-for="AuthorUsername" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<a class="btn btn-danger" asp-controller="Admin" asp-action="Index">Return back</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}